---
tls:
  certificates:
    - certFile: /etc/traefik/certs/wildcard.pem
    - keyFile: /etc/traefik/certs/wildcard-key.pem
  stores:
    default:
      defaultCertificates:
        - certFile: /etc/traefik/certs/wildcard.pem
        - keyFile: /etc/traefik/certs/wildcard-key.pem